codecov:
  max_report_age: off

coverage:
  status:
    patch:
      default:
        threshold: 100% # change by 5-10% after writing most of the tests
    project:
      default:
        threshold: 100% # change by 5-10% after writing most of the tests
