name: build

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.20, 2.13.13]
        java: ["temurin:1.17.0.9"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4

    - name: Cache build
      uses: coursier/cache-action@v6

    - name: Install coursier
      uses: coursier/setup-action@v1
      with:
        jvm: ${{ matrix.java }}

    - name: Test
      run: |
        export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS --add-opens=java.base/java.lang=ALL-UNNAMED";
        sbt ++${{ matrix.scala }} clean coverage test scalafmtCheckAll scalafmtSbtCheck "scalafixAll --check"

    - name: Coverage
      run: sbt ++${{ matrix.scala }} coverageReport

    - name: Send coverage report to codecov
      uses: codecov/codecov-action@v4.5.0

#    - name: Send coverage report to codacy
#      uses: codacy/codacy-coverage-reporter-action@master
