name: release
on:
  push:
    branches: 
      - main
      - develop/*
    tags: ["v*.*.*"]
  pull_request:

env:
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: "zulu:8.0.402"
      - name: Publish
        if: ${{ !github.event.pull_request.head.repo.fork }}
        run: sbt clean ci-release
